print("====================================")
print("   EXAMEN TRANSVERSAL DRY7122")
print("====================================")
print("Integrantes del grupo:")
print("")
print("1. Fiorela Loch")
print("2. Gabriel Alegria")
print("3. Pedro Orellana")
print("4. Bastian Lazcano")
